(()=>{
const homeCourses = [
  {id:'web',title:'Complete Web Development Bootcamp',category:'Development',topic:'Web Development',provider:'Arjun Mehta',level:'Beginner',duration:'18h 30m',students:'12.4k',rating:'4.9',reviews:'2,104',tag:'Bestseller',image:'https://images.unsplash.com/photo-1498050108023-c5249f4df085?auto=format&fit=crop&w=700&q=80',url:'https://www.freecodecamp.org/learn/'},
  {id:'python',title:'Python for Everybody: Zero to Projects',category:'Data',topic:'Python',provider:'Neha Kapoor',level:'Beginner',duration:'14h 20m',students:'18.1k',rating:'4.8',reviews:'3,220',tag:'Popular',image:'https://images.unsplash.com/photo-1526379095098-d400fd0bf935?auto=format&fit=crop&w=700&q=80',url:'https://www.kaggle.com/learn/python'},
  {id:'ai',title:'Artificial Intelligence & Machine Learning',category:'Data',topic:'AI & Machine Learning',provider:'Dr. Rohan Iyer',level:'Intermediate',duration:'22h 10m',students:'9.8k',rating:'4.9',reviews:'1,876',tag:'Trending',image:'https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=700&q=80',url:'https://grow.google/ai/'},
  {id:'uiux',title:'UI/UX Design: Create Products People Love',category:'Design',topic:'UI/UX Design',provider:'Meera Shah',level:'Beginner',duration:'11h 45m',students:'7.3k',rating:'4.7',reviews:'1,190',tag:'New',image:'https://images.unsplash.com/photo-1558655146-9f40138edfeb?auto=format&fit=crop&w=700&q=80',url:'https://www.figma.com/resource-library/'},
  {id:'marketing',title:'Digital Marketing Strategy Masterclass',category:'Marketing',topic:'Digital Marketing',provider:'Vikram Rao',level:'Intermediate',duration:'9h 15m',students:'6.9k',rating:'4.8',reviews:'986',tag:'Popular',image:'https://images.unsplash.com/photo-1460925895917-afdab827c52f?auto=format&fit=crop&w=700&q=80',url:'https://skillshop.withgoogle.com/'},
  {id:'cyber',title:'Cyber Security Foundations',category:'Development',topic:'Cyber Security',provider:'Kiran Das',level:'Beginner',duration:'12h 05m',students:'8.2k',rating:'4.8',reviews:'1,402',tag:'New',image:'https://images.unsplash.com/photo-1563013544-824ae1b704d3?auto=format&fit=crop&w=700&q=80',url:'https://www.netacad.com/'},
  {id:'cloud',title:'Cloud Computing with AWS Essentials',category:'Development',topic:'Cloud Computing',provider:'Aman Verma',level:'Intermediate',duration:'16h 40m',students:'5.6k',rating:'4.7',reviews:'834',tag:'Trending',image:'https://images.unsplash.com/photo-1451187580459-43490279c0fa?auto=format&fit=crop&w=700&q=80',url:'https://skillbuilder.aws/'},
  {id:'analytics',title:'Data Analytics with Excel and Power BI',category:'Data',topic:'Data Analytics',provider:'Sara Joseph',level:'Beginner',duration:'13h 25m',students:'10.7k',rating:'4.9',reviews:'1,655',tag:'Bestseller',image:'https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&w=700&q=80',url:'https://skillsbuild.org/students/course-catalog/data'}
];

const categories=[['Web Development','fa-code',184],['Full Stack','fa-layer-group',126],['AI & Machine Learning','fa-brain',98],['Data Science','fa-chart-pie',112],['Python','fa-brands fa-python',156],['UI/UX Design','fa-pen-ruler',89],['Digital Marketing','fa-bullhorn',104],['Cyber Security','fa-shield-halved',76],['Cloud Computing','fa-cloud',68],['Mobile Apps','fa-mobile-screen',83],['Graphic Design','fa-palette',92],['Business Skills','fa-briefcase',141],['Java','fa-brands fa-java',71],['Data Analytics','fa-chart-line',118]];
const palette=[['#ece9ff','#6250d9'],['#e6f8fb','#159bb1'],['#fff0ee','#e56d55'],['#eef5ff','#4e7bc5']];
const categoryGrid=document.getElementById('categoryGrid');
categoryGrid.innerHTML=categories.map((c,i)=>`<button class="category-card" data-category="${c[0]}" style="--cat-bg:${palette[i%4][0]};--cat-color:${palette[i%4][1]}"><span><i class="fa-solid ${c[1]}"></i></span><h3>${c[0]}</h3><small>${c[2]} courses</small></button>`).join('');

let activeCategory='All',activeLevel='All',query='';
const saved=new Set(JSON.parse(localStorage.getItem('skillHubWishlist')||'[]'));
const homeCoursesGrid=document.getElementById('coursesGrid');
const escapeText=value=>String(value).replace(/[&<>'"]/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[char]));
function courseCard(course){return `<article class="platform-course-card"><div class="course-thumb"><img src="${course.image}" alt="${escapeText(course.topic)} course thumbnail" width="700" height="420" loading="lazy"><span class="course-label">${course.tag}</span><button class="wishlist-btn ${saved.has(course.id)?'saved':''}" data-wishlist="${course.id}" aria-label="Save ${escapeText(course.title)}"><i class="${saved.has(course.id)?'fa-solid':'fa-regular'} fa-heart"></i></button></div><div class="course-body"><span class="course-provider">${course.topic} · ${course.provider}</span><h3>${course.title}</h3><div class="rating-row"><strong>${course.rating}</strong> <span class="stars">★★★★★</span> (${course.reviews})</div><div class="course-meta-row"><span><i class="fa-regular fa-clock"></i> ${course.duration}</span><span><i class="fa-solid fa-signal"></i> ${course.level}</span><span><i class="fa-solid fa-users"></i> ${course.students}</span></div><div class="course-card-footer"><strong>FREE</strong><a href="${course.url}" target="_blank" rel="noopener">View course <i class="fa-solid fa-arrow-right"></i></a></div></div></article>`}
function renderCourses(){const list=homeCourses.filter(c=>(activeCategory==='All'||c.category===activeCategory||c.topic.includes(activeCategory))&&(activeLevel==='All'||c.level===activeLevel)&&(`${c.title} ${c.topic} ${c.provider}`.toLowerCase().includes(query.toLowerCase())));homeCoursesGrid.innerHTML=list.map(courseCard).join('');document.getElementById('emptyState').hidden=Boolean(list.length);}
function compactCard(c){return `<a class="compact-card" href="${c.url}" target="_blank" rel="noopener"><img src="${c.image}" alt="" width="250" height="180" loading="lazy"><div><span>${c.topic}</span><h3>${c.title}</h3><small><b class="stars">★</b> ${c.rating} · ${c.duration} · ${c.level}</small></div></a>`}
document.getElementById('trendingGrid').innerHTML=homeCourses.slice(1,4).map(compactCard).join('');document.getElementById('recentGrid').innerHTML=homeCourses.slice(5,8).map(compactCard).join('');
document.getElementById('instructorGrid').innerHTML=[['Arjun Mehta','Web Development','https://images.unsplash.com/photo-1560250097-0b93528c311a?auto=format&fit=crop&w=240&q=80','48k'],['Neha Kapoor','Data Science & Python','https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=240&q=80','36k'],['Dr. Rohan Iyer','AI & Machine Learning','https://images.unsplash.com/photo-1568602471122-7832951cc4c5?auto=format&fit=crop&w=240&q=80','29k'],['Meera Shah','Product & UX Design','https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&w=240&q=80','24k']].map(i=>`<article class="instructor-card"><img src="${i[2]}" alt="${i[0]}" width="164" height="164" loading="lazy"><h3>${i[0]}</h3><p>${i[1]}</p><small><i class="fa-solid fa-user-group"></i> ${i[3]} students · <span class="stars">★ 4.9</span></small></article>`).join('');

function toast(message){const el=document.getElementById('homeToast');el.textContent=message;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),2200)}
function updateWishlist(){document.getElementById('wishlistCount').textContent=saved.size;localStorage.setItem('skillHubWishlist',JSON.stringify([...saved]));}
document.addEventListener('click',event=>{const wish=event.target.closest('[data-wishlist]');if(wish){const id=wish.dataset.wishlist;saved.has(id)?saved.delete(id):saved.add(id);updateWishlist();renderCourses();toast(saved.has(id)?'Course added to your wishlist':'Course removed from your wishlist');return}const filter=event.target.closest('[data-filter]');if(filter){activeCategory=filter.dataset.filter;document.querySelectorAll('[data-filter]').forEach(b=>b.classList.toggle('active',b===filter));renderCourses()}const cat=event.target.closest('[data-category]');if(cat){query=cat.dataset.category;document.getElementById('searchInput').value=query;renderCourses();document.getElementById('featured').scrollIntoView({behavior:'smooth'})}const suggestion=event.target.closest('[data-search]');if(suggestion){query=suggestion.dataset.search;document.getElementById('searchInput').value=query;renderCourses();document.getElementById('featured').scrollIntoView({behavior:'smooth'})}});
document.getElementById('heroSearch').addEventListener('submit',event=>{event.preventDefault();query=document.getElementById('searchInput').value.trim();renderCourses();document.getElementById('featured').scrollIntoView({behavior:'smooth'})});
document.getElementById('searchInput').addEventListener('input',event=>{query=event.target.value;renderCourses()});document.getElementById('levelFilter').addEventListener('change',event=>{activeLevel=event.target.value;renderCourses()});
document.getElementById('courseNext').addEventListener('click',()=>homeCoursesGrid.scrollBy({left:320,behavior:'smooth'}));document.getElementById('coursePrev').addEventListener('click',()=>homeCoursesGrid.scrollBy({left:-320,behavior:'smooth'}));
const themeToggle=document.getElementById('themeToggle');function applyTheme(theme){document.body.classList.toggle('dark',theme==='dark');themeToggle.innerHTML=`<i class="fa-solid fa-${theme==='dark'?'sun':'moon'}"></i>`;localStorage.setItem('skillHubTheme',theme)}applyTheme(localStorage.getItem('skillHubTheme')||'light');themeToggle.addEventListener('click',()=>applyTheme(document.body.classList.contains('dark')?'light':'dark'));
document.getElementById('wishlistButton').addEventListener('click',()=>{query='';activeCategory='All';homeCoursesGrid.innerHTML=homeCourses.filter(c=>saved.has(c.id)).map(courseCard).join('');document.getElementById('emptyState').hidden=saved.size>0;if(!saved.size)toast('Your wishlist is empty');document.getElementById('featured').scrollIntoView({behavior:'smooth'})});
updateWishlist();renderCourses();
})();
